// milestones/milestone-main/ProductApp/product-app/src/app/components/product-list/product-list.component.ts
import { Component } from '@angular/core';
import { ProductService, Product } from '../../services/product.service';

@Component({
  selector: 'app-product-list',
  standalone: false,
  templateUrl: './product-list.component.html',
  styleUrls: ['./product-list.component.scss'],
})
export class ProductListComponent {
  products: Product[] = [];
  searchText: string = '';

  get filteredProducts(): Product[] {
    return this.products.filter(product =>
      product.name.toLowerCase().includes(this.searchText.toLowerCase())
     // product.category.toLowerCase().includes(this.searchText.toLowerCase())
    );
  }

  constructor(private productService: ProductService) {}

  ngOnInit(): void {
    this.productService.getProducts().subscribe((data) => {
      this.products = data;
    });
  }

  deleteProduct(id: number): void {
    this.productService.deleteProduct(id).subscribe(() => {
      this.products = this.products.filter(product => product.product_id !== id);
    });
  }
}

<div class="inventory-container">
  <div class="header-section mb-4">
    <h1 class="text-primary">Inventory Management</h1>
    <p class="text-muted">Track and manage your product inventory</p>
  </div>

  <div class="search-section mb-4">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search products..." [(ngModel)]="searchText">
      <div class="input-group-append">
        <span class="input-group-text"><i class="fas fa-search"></i></span>
      </div>
    </div>
  </div>

  <div class="inventory-summary mb-3">
    <div class="alert alert-info">
      <i class="fas fa-box-open"></i> Total Products: {{ filteredProducts.length }}
    </div>
  </div>

  <div class="table-responsive shadow-sm">
    <table class="table table-hover">
      <thead class="bg-primary text-white">
        <tr>
          <th scope="col">Name</th>
          <th scope="col">Category</th>
          <th scope="col">Quantity</th>
          <th scope="col">Condition</th>
          <th scope="col">Price</th>
          <th scope="col" class="text-center">Actions</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let product of filteredProducts">
          <td class="align-middle">{{ product.name }}</td>
          <td class="align-middle"><span class="badge bg-secondary">{{ product.category }}</span></td>
          <td class="align-middle">
            <span [class]="product.quantity <= 5 ? 'text-danger' : 'text-success'">
              {{ product.quantity }}
            </span>
          </td>
          <td class="align-middle">{{ product.condition }}</td>
          <td class="align-middle">{{ product.price | currency }}</td>
          <td class="text-center">
            <button class="btn btn-outline-info btn-sm me-2" [routerLink]="['/products', product.product_id]">
              <i class="fas fa-eye"></i> View
            </button>
            <button class="btn btn-outline-primary btn-sm me-2" [routerLink]="['/products/edit', product.product_id]">
              <i class="fas fa-edit"></i> Edit
            </button>
            <button class="btn btn-outline-danger btn-sm" (click)="deleteProduct(product.product_id)">
              <i class="fas fa-trash"></i> Delete
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<style>
.inventory-container {
  padding: 2rem;
  background-color: #f8f9fa;
  min-height: 100vh;
}

.header-section {
  border-bottom: 2px solid #e9ecef;
  padding-bottom: 1rem;
}

.table-responsive {
  background-color: white;
  border-radius: 8px;
  overflow: hidden;
}

.badge {
  padding: 0.5em 1em;
}

.btn {
  transition: all 0.3s;
}

.btn:hover {
  transform: translateY(-1px);
}

.inventory-summary {
  font-size: 1.1rem;
}
</style>

// milestones/milestone-main/ProductApp/product-app-react/src/components/ProductList.js
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import * as ProductService from '../services/productService';

const ProductList = () => {
    const [products, setProducts] = useState([]);
    const [searchText, setSearchText] = useState('');

    useEffect(() => {
        loadProducts();
    }, []);

    const loadProducts = async () => {
        try {
            const data = await ProductService.getProducts();
            setProducts(data);
        } catch (error) {
            console.error('Error loading products:', error);
        }
    };

    const handleDelete = async (id) => {
        try {
            await ProductService.deleteProduct(id);
            setProducts(products.filter(product => product.product_id !== id));
        } catch (error) {
            console.error('Error deleting product:', error);
        }
    };

    const filteredProducts = products.filter(product =>
        product.name.toLowerCase().includes(searchText.toLowerCase())
    );

    return (
        <div className="inventory-container">
            <div className="header-section mb-4">
                <h1 className="text-primary">Inventory Management</h1>
                <p className="text-muted">Track and manage your product inventory</p>
            </div>

            <div className="search-section mb-4">
                <div className="input-group">
                    <input
                        type="text"
                        className="form-control"
                        placeholder="Search products..."
                        value={searchText}
                        onChange={(e) => setSearchText(e.target.value)}
                    />
                </div>
            </div>

            <div className="inventory-summary mb-3">
                <div className="alert alert-info">
                    Total Products: {filteredProducts.length}
                </div>
            </div>

            <div className="table-responsive shadow-sm">
                <table className="table table-hover">
                    <thead className="bg-primary text-white">
                        <tr>
                            <th>Name</th>
                            <th>Category</th>
                            <th>Quantity</th>
                            <th>Condition</th>
                            <th>Price</th>
                            <th className="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {filteredProducts.map((product) => (
                            <tr key={product.product_id}>
                                <td>{product.name}</td>
                                <td>
                                    <span className="badge bg-secondary">
                                        {product.category}
                                    </span>
                                </td>
                                <td>
                                    <span className={product.quantity <= 5 ? 'text-danger' : 'text-success'}>
                                        {product.quantity}
                                    </span>
                                </td>
                                <td>{product.condition}</td>
                                <td>${product.price.toFixed(2)}</td>
                                <td className="text-center">
                                    <Link
                                        to={`/products/${product.product_id}`}
                                        className="btn btn-outline-info btn-sm me-2"
                                    >
                                        View
                                    </Link>
                                    <Link
                                        to={`/products/edit/${product.product_id}`}
                                        className="btn btn-outline-primary btn-sm me-2"
                                    >
                                        Edit
                                    </Link>
                                    <button
                                        className="btn btn-outline-danger btn-sm"
                                        onClick={() => handleDelete(product.product_id)}
                                    >
                                        Delete
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default ProductList;
